/*-
 * Copyright (c) 2003-2013 Broadcom Corporation
 * All Rights Reserved
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY BROADCOM ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL BROADCOM OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * #BRCM_2# */
//
// autogenerated by RegUtils.pm on 2011/12/22 12:13 format: mdioFullReg
//
NLM_C45_WRITE (0, 0, 0, 1,0xca42, 0x0100); // 10:8 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca44, 0x81f8); // 15:12= 0x8
NLM_C45_WRITE (0, 0, 0, 1,0xca44, 0x8218); //  9:5 = 0x10
NLM_C45_WRITE (0, 0, 0, 1,0xca46, 0x0100); //  8:8 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca46, 0x0900); // 11:9 = 0x4
NLM_C45_WRITE (0, 0, 0, 1,0xcb0e, 0x1000); // 13:12= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca4c, 0x0002); //  5:0 = 0x2
NLM_C45_WRITE (0, 0, 0, 1,0xca12, 0x0100); // 10:8 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca14, 0x81f8); // 15:12= 0x8
NLM_C45_WRITE (0, 0, 0, 1,0xca14, 0x8218); //  9:5 = 0x10
NLM_C45_WRITE (0, 0, 0, 1,0xca16, 0x0100); //  8:8 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca16, 0x0900); // 11:9 = 0x4
NLM_C45_WRITE (0, 0, 0, 1,0xcb06, 0x1000); // 13:12= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca1c, 0x0002); //  5:0 = 0x2
NLM_C45_WRITE (0, 0, 0, 1,0xca42, 0x0900); // 13:11= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca43, 0x2492); // 14:12= 0x2
NLM_C45_WRITE (0, 0, 0, 1,0xc246, 0x0181); //  9:7 = 0x3
NLM_C45_WRITE (0, 0, 0, 1,0xc242, 0x8100); //  2:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc240, 0x1000); //  7:4 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc240, 0x3800); // 13:11= 0x7
NLM_C45_WRITE (0, 0, 0, 1,0xc242, 0x0100); // 15:13= 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc246, 0x0180); //  0:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc246, 0x0182); //  1:1 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xc243, 0x07e1); //  4:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xc243, 0x07e1); // 10:5 = 0x3f
NLM_C45_WRITE (0, 0, 0, 1,0xc243, 0x17e1); // 15:11= 0x2
NLM_C45_WRITE (0, 0, 0, 1,0xcb0b, 0x0001); //  1:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcb0b, 0x0011); //  5:4 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcb0b, 0x0311); //  9:8 = 0x3
NLM_C45_WRITE (0, 0, 0, 1,0xcb0b, 0x0f11); // 11:10= 0x3
NLM_C45_WRITE (0, 0, 0, 1,0xcb0b, 0x3f11); // 13:12= 0x3
NLM_C45_WRITE (0, 0, 0, 1,0xcb0b, 0xff11); // 15:14= 0x3
NLM_C45_WRITE (0, 0, 0, 1,0xcc00, 0x00f6); //  7:0 = 0xf6
NLM_C45_WRITE (0, 0, 0, 1,0xcc02, 0x0081); //  7:7 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcc02, 0x0001); //  7:7 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc07, 0x0117); //  4:0 = 0x17
NLM_C45_WRITE (0, 0, 0, 1,0xcc08, 0x07df); //  5:0 = 0x1f
NLM_C45_WRITE (0, 0, 0, 1,0xcc08, 0x07df); // 11:6 = 0x1f
NLM_C45_WRITE (0, 0, 0, 1,0xcc09, 0x07df); //  5:0 = 0x1f
NLM_C45_WRITE (0, 0, 0, 1,0xcc09, 0x07df); // 11:6 = 0x1f
NLM_C45_WRITE (0, 0, 0, 1,0xcc07, 0x0017); //  8:5 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc0e, 0x0001); //  0:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcc0e, 0x0003); //  1:1 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcc0e, 0x0007); //  2:2 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcc0e, 0x0006); //  0:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc0e, 0x0004); //  1:1 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc0e, 0x0000); //  2:2 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc02, 0x0021); //  5:5 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcc04, 0x0001); //  0:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcc04, 0x00b5); //  8:1 = 0x5a
NLM_C45_WRITE (0, 0, 0, 1,0xcc11, 0x4904); //  5:3 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc11, 0x4804); //  8:6 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc11, 0x4004); // 11:9 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc11, 0x0004); // 14:12= 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcc11, 0x0000); //  2:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xcb02, 0x00f0); //  7:4 = 0xf
NLM_C45_WRITE (0, 0, 0, 1,0xcb02, 0x00ff); //  3:0 = 0xf
NLM_C45_WRITE (0, 0, 0, 1,0xcb21, 0x1000); // 15:12= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca01, 0x0001); //  0:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca01, 0x0011); //  7:1 = 0x8
NLM_C45_WRITE (0, 0, 0, 1,0xcb1b, 0x1000); // 15:12= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca51, 0x0001); //  0:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca51, 0x0011); //  7:1 = 0x8
NLM_C45_WRITE (0, 0, 0, 1,0xc2c3, 0x000f); //  3:0 = 0xf
NLM_C45_WRITE (0, 0, 0, 1,0xc2ca, 0x43c0); // 15:11= 0x8
NLM_C45_WRITE (0, 0, 0, 1,0xc2d0, 0x43c0); // 15:11= 0x8
NLM_C45_WRITE (0, 0, 0, 1,0xc2d6, 0x43c0); // 15:11= 0x8
NLM_C45_WRITE (0, 0, 0, 1,0xc2dc, 0x43c0); // 15:11= 0x8
NLM_C45_WRITE (0, 0, 0, 1,0xc2f1, 0x5f15); //  5:1 = 0xa
NLM_C45_WRITE (0, 0, 0, 1,0xc2f1, 0x5e15); //  8:6 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2f5, 0x5f15); //  5:1 = 0xa
NLM_C45_WRITE (0, 0, 0, 1,0xc2f5, 0x5e15); //  8:6 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2f9, 0x5f15); //  5:1 = 0xa
NLM_C45_WRITE (0, 0, 0, 1,0xc2f9, 0x5e15); //  8:6 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2fd, 0x5f15); //  5:1 = 0xa
NLM_C45_WRITE (0, 0, 0, 1,0xc2fd, 0x5e15); //  8:6 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2e8, 0x0100); //  8:0 = 0x100
NLM_C45_WRITE (0, 0, 0, 1,0xc2e9, 0x0100); //  8:0 = 0x100
NLM_C45_WRITE (0, 0, 0, 1,0xc2ea, 0x0100); //  8:0 = 0x100
NLM_C45_WRITE (0, 0, 0, 1,0xc2eb, 0x0100); //  8:0 = 0x100
NLM_C45_WRITE (0, 0, 0, 1,0xc2e6, 0x0800); // 11:11= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xc2e6, 0x0000); // 11:11= 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc017, 0xdf20); // 13:13= 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc010, 0x4000); // 14:14= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcd40, 0x0001); //  3:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xc010, 0x6000); // 13:13= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcc05, 0x001f); //  2:0 = 0x7
NLM_C45_WRITE (0, 0, 0, 1,0xcc03, 0x0020); //  9:0 = 0x20
NLM_C45_WRITE (0, 0, 0, 1,0xc019, 0x1531); // 10:10= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xff2a, 0x004a); // 
NLM_C45_WRITE (0, 0, 0, 1,0xd008, 0x0001); //  0:0 = 0x1

//sleep 100000	   # us
for(i=0;i<100000;i++) NLM_C45_PRINTF(".");
// WARNING: mdtrace, reg  1.d000 write value (5200) doesn't match read back (5000)

NLM_C45_WRITE (0, 0, 0, 1,0xd000, 0x5200);   

//sleep 100000	   # us
for(i=0;i<100000;i++) NLM_C45_PRINTF(".");

NLM_C45_WRITE (0, 0, 0, 1,0xd800, 0x2fff);   
NLM_C45_WRITE (0, 0, 0, 1,0xd801, 0x300f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd802, 0x2ff4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd803, 0x3ef4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd804, 0x20ae);   
NLM_C45_WRITE (0, 0, 0, 1,0xd805, 0x301e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd806, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd807, 0x22c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd808, 0x3ef4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd809, 0x400e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd80a, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd80b, 0x220e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd80c, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd80d, 0x2124);   
NLM_C45_WRITE (0, 0, 0, 1,0xd80e, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd80f, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd810, 0x23fe);   
NLM_C45_WRITE (0, 0, 0, 1,0xd811, 0x3c1e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd812, 0x2214);   
NLM_C45_WRITE (0, 0, 0, 1,0xd813, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd814, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd815, 0x20a4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd816, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd817, 0x2dfe);   
NLM_C45_WRITE (0, 0, 0, 1,0xd818, 0x307e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd819, 0x6e24);   
NLM_C45_WRITE (0, 0, 0, 1,0xd81a, 0x6e24);   
NLM_C45_WRITE (0, 0, 0, 1,0xd81b, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd81c, 0x20e4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd81d, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd81e, 0x402e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd81f, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd820, 0x400e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd821, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd822, 0x2014);   
NLM_C45_WRITE (0, 0, 0, 1,0xd823, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd824, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd825, 0x6e8f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd826, 0x400e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd827, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd828, 0x2044);   
NLM_C45_WRITE (0, 0, 0, 1,0xd829, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd82a, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd82b, 0x6e8f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd82c, 0x201e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd82d, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd82e, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd82f, 0x20d4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd830, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd831, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd832, 0x6e8f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd833, 0x21fe);   
NLM_C45_WRITE (0, 0, 0, 1,0xd834, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd835, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd836, 0x20e4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd837, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd838, 0x404e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd839, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd83a, 0x400e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd83b, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd83c, 0x21f5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd83d, 0x3005);   
NLM_C45_WRITE (0, 0, 0, 1,0xd83e, 0xb805);   
NLM_C45_WRITE (0, 0, 0, 1,0xd83f, 0x8556);   
NLM_C45_WRITE (0, 0, 0, 1,0xd840, 0x8557);   
NLM_C45_WRITE (0, 0, 0, 1,0xd841, 0x8558);   
NLM_C45_WRITE (0, 0, 0, 1,0xd842, 0x8559);   
NLM_C45_WRITE (0, 0, 0, 1,0xd843, 0x855a);   
NLM_C45_WRITE (0, 0, 0, 1,0xd844, 0x400d);   
NLM_C45_WRITE (0, 0, 0, 1,0xd845, 0x6d8f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd846, 0x2032);   
NLM_C45_WRITE (0, 0, 0, 1,0xd847, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd848, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd849, 0x2132);   
NLM_C45_WRITE (0, 0, 0, 1,0xd84a, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd84b, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd84c, 0x21c2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd84d, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd84e, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd84f, 0x2302);   
NLM_C45_WRITE (0, 0, 0, 1,0xd850, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd851, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd852, 0x23a2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd853, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd854, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd855, 0x24c2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd856, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd857, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd858, 0x2562);   
NLM_C45_WRITE (0, 0, 0, 1,0xd859, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd85a, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd85b, 0x6f7e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd85c, 0x4004);   
NLM_C45_WRITE (0, 0, 0, 1,0xd85d, 0xb814);   
NLM_C45_WRITE (0, 0, 0, 1,0xd85e, 0x5e43);   
NLM_C45_WRITE (0, 0, 0, 1,0xd85f, 0x03d7);   
NLM_C45_WRITE (0, 0, 0, 1,0xd860, 0x2032);   
NLM_C45_WRITE (0, 0, 0, 1,0xd861, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd862, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd863, 0x200e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd864, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd865, 0x0002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd866, 0xd01e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd867, 0x6e8f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd868, 0x20fe);   
NLM_C45_WRITE (0, 0, 0, 1,0xd869, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd86a, 0xb80e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd86b, 0xd01d);   
NLM_C45_WRITE (0, 0, 0, 1,0xd86c, 0x5de3);   
NLM_C45_WRITE (0, 0, 0, 1,0xd86d, 0x249e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd86e, 0x301e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd86f, 0x135e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd870, 0x6f7e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd871, 0x6f7e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd872, 0x20d4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd873, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd874, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd875, 0x20e4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd876, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd877, 0x404e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd878, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd879, 0x400e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd87a, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd87b, 0x6f7e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd87c, 0x2044);   
NLM_C45_WRITE (0, 0, 0, 1,0xd87d, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd87e, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd87f, 0x6f7e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd880, 0x2014);   
NLM_C45_WRITE (0, 0, 0, 1,0xd881, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd882, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd883, 0x200e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd884, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd885, 0x2124);   
NLM_C45_WRITE (0, 0, 0, 1,0xd886, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd887, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd888, 0x2504);   
NLM_C45_WRITE (0, 0, 0, 1,0xd889, 0x3cd4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd88a, 0x4015);   
NLM_C45_WRITE (0, 0, 0, 1,0xd88b, 0x65c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd88c, 0x2514);   
NLM_C45_WRITE (0, 0, 0, 1,0xd88d, 0x3cd4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd88e, 0x64d5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd88f, 0xb145);   
NLM_C45_WRITE (0, 0, 0, 1,0xd890, 0xb115);   
NLM_C45_WRITE (0, 0, 0, 1,0xd891, 0x65c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd892, 0x2bd2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd893, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd894, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd895, 0x678f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd896, 0x2514);   
NLM_C45_WRITE (0, 0, 0, 1,0xd897, 0x3cd4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd898, 0x64d5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd899, 0xb145);   
NLM_C45_WRITE (0, 0, 0, 1,0xd89a, 0xb105);   
NLM_C45_WRITE (0, 0, 0, 1,0xd89b, 0x65c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd89c, 0x2bd2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd89d, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd89e, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd89f, 0x6f78);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a0, 0xe78e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a1, 0x22c5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a2, 0x3ef5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a3, 0x6ec5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a4, 0x2084);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a5, 0x3034);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a6, 0x2005);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a7, 0x3d75);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a8, 0xc451);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8a9, 0x2f62);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8aa, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ab, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ac, 0x2444);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ad, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ae, 0x2ed2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8af, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b0, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b1, 0x2144);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b2, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b3, 0x2ed2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b4, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b5, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b6, 0x2f02);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b7, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b8, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8b9, 0x28c2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ba, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8bb, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8bc, 0x0000);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8bd, 0x628f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8be, 0x4007);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8bf, 0x2524);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c0, 0x3cd4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c1, 0x64d5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c2, 0x2005);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c3, 0x9575);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c4, 0x65c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c5, 0x678f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c6, 0x2dd2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c7, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c8, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8c9, 0x6f77);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ca, 0x2514);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8cb, 0x3cd4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8cc, 0x64d5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8cd, 0xbd05);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ce, 0xbf45);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8cf, 0x2db2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d0, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d1, 0x5553);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d2, 0x1302);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d3, 0x2006);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d4, 0x3016);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d5, 0x5763);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d6, 0x13c2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d7, 0xd017);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d8, 0x2bf2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8d9, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8da, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8db, 0x6f72);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8dc, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8dd, 0x628f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8de, 0x2514);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8df, 0x3cd4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e0, 0x64d5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e1, 0x4026);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e2, 0x9655);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e3, 0x65c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e4, 0x648f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e5, 0x401d);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e6, 0x2f22);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e7, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e8, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8e9, 0x6f74);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ea, 0x2fd6);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8eb, 0x3ff6);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ec, 0x8655);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ed, 0x65c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ee, 0x6f72);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ef, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f0, 0x22cd);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f1, 0x301d);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f2, 0x2108);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f3, 0x3808);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f4, 0x628f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f5, 0x5dd3);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f6, 0x2012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f7, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f8, 0x1302);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8f9, 0x63a8);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8fa, 0x2b72);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8fb, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8fc, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8fd, 0xdffd);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8fe, 0x2f52);   
NLM_C45_WRITE (0, 0, 0, 1,0xd8ff, 0x3012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd900, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd901, 0x6f72);   
NLM_C45_WRITE (0, 0, 0, 1,0xd902, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd903, 0x2214);   
NLM_C45_WRITE (0, 0, 0, 1,0xd904, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd905, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd906, 0x2ef4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd907, 0x3ff4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd908, 0x8e4e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd909, 0x2214);   
NLM_C45_WRITE (0, 0, 0, 1,0xd90a, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd90b, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd90c, 0x2104);   
NLM_C45_WRITE (0, 0, 0, 1,0xd90d, 0x3004);   
NLM_C45_WRITE (0, 0, 0, 1,0xd90e, 0x9e4e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd90f, 0x2214);   
NLM_C45_WRITE (0, 0, 0, 1,0xd910, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd911, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd912, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd913, 0x2294);   
NLM_C45_WRITE (0, 0, 0, 1,0xd914, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd915, 0x64db);   
NLM_C45_WRITE (0, 0, 0, 1,0xd916, 0x8bbc);   
NLM_C45_WRITE (0, 0, 0, 1,0xd917, 0xb84b);   
NLM_C45_WRITE (0, 0, 0, 1,0xd918, 0x300c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd919, 0xdf0b);   
NLM_C45_WRITE (0, 0, 0, 1,0xd91a, 0xdf0c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd91b, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd91c, 0xc5b5);   
NLM_C45_WRITE (0, 0, 0, 1,0xd91d, 0xc6c6);   
NLM_C45_WRITE (0, 0, 0, 1,0xd91e, 0x855e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd91f, 0xb84e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd920, 0x866c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd921, 0xb84c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd922, 0xb60c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd923, 0x9cee);   
NLM_C45_WRITE (0, 0, 0, 1,0xd924, 0x20a4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd925, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd926, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd927, 0x20e4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd928, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd929, 0x202e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd92a, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd92b, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd92c, 0x200e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd92d, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd92e, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd92f, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd930, 0x22b4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd931, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd932, 0x64db);   
NLM_C45_WRITE (0, 0, 0, 1,0xd933, 0x8bbc);   
NLM_C45_WRITE (0, 0, 0, 1,0xd934, 0xb84b);   
NLM_C45_WRITE (0, 0, 0, 1,0xd935, 0xb80c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd936, 0xb84c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd937, 0xdf0b);   
NLM_C45_WRITE (0, 0, 0, 1,0xd938, 0xdf0c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd939, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd93a, 0xc7b7);   
NLM_C45_WRITE (0, 0, 0, 1,0xd93b, 0xc8c8);   
NLM_C45_WRITE (0, 0, 0, 1,0xd93c, 0x877e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd93d, 0xb84e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd93e, 0x888c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd93f, 0xb84c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd940, 0xb60c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd941, 0x9cee);   
NLM_C45_WRITE (0, 0, 0, 1,0xd942, 0x20b4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd943, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd944, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd945, 0x20e4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd946, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd947, 0x402e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd948, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd949, 0x400e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd94a, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd94b, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd94c, 0x22a4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd94d, 0x3ca4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd94e, 0x64db);   
NLM_C45_WRITE (0, 0, 0, 1,0xd94f, 0x8bbc);   
NLM_C45_WRITE (0, 0, 0, 1,0xd950, 0xb84b);   
NLM_C45_WRITE (0, 0, 0, 1,0xd951, 0xb80c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd952, 0xb84c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd953, 0xdf0b);   
NLM_C45_WRITE (0, 0, 0, 1,0xd954, 0xdf0c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd955, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd956, 0xc9b9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd957, 0xcaca);   
NLM_C45_WRITE (0, 0, 0, 1,0xd958, 0x899e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd959, 0xb84e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd95a, 0x8aac);   
NLM_C45_WRITE (0, 0, 0, 1,0xd95b, 0xb84c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd95c, 0xb60c);   
NLM_C45_WRITE (0, 0, 0, 1,0xd95d, 0x9cee);   
NLM_C45_WRITE (0, 0, 0, 1,0xd95e, 0x20c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd95f, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd960, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd961, 0x20e4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd962, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd963, 0x402e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd964, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd965, 0x400e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd966, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd967, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd968, 0x628f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd969, 0x20a4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd96a, 0x3004);   
NLM_C45_WRITE (0, 0, 0, 1,0xd96b, 0x64d9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd96c, 0x899e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd96d, 0xbf0e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd96e, 0xbf4e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd96f, 0x4012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd970, 0x2f0e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd971, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd972, 0x2054);   
NLM_C45_WRITE (0, 0, 0, 1,0xd973, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd974, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd975, 0x2064);   
NLM_C45_WRITE (0, 0, 0, 1,0xd976, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd977, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd978, 0x8ee9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd979, 0xbe0e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd97a, 0xbf4e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd97b, 0x5e23);   
NLM_C45_WRITE (0, 0, 0, 1,0xd97c, 0x0382);   
NLM_C45_WRITE (0, 0, 0, 1,0xd97d, 0x0008);   
NLM_C45_WRITE (0, 0, 0, 1,0xd97e, 0x401e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd97f, 0x99e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd980, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd981, 0x280e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd982, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd983, 0x63ae);   
NLM_C45_WRITE (0, 0, 0, 1,0xd984, 0x0008);   
NLM_C45_WRITE (0, 0, 0, 1,0xd985, 0x2fee);   
NLM_C45_WRITE (0, 0, 0, 1,0xd986, 0x3ffe);   
NLM_C45_WRITE (0, 0, 0, 1,0xd987, 0x89e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd988, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd989, 0x280e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd98a, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd98b, 0x63ae);   
NLM_C45_WRITE (0, 0, 0, 1,0xd98c, 0x6f72);   
NLM_C45_WRITE (0, 0, 0, 1,0xd98d, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd98e, 0x628f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd98f, 0x20a4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd990, 0x3004);   
NLM_C45_WRITE (0, 0, 0, 1,0xd991, 0x64d9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd992, 0x899e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd993, 0xbf0e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd994, 0xbf4e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd995, 0x4012);   
NLM_C45_WRITE (0, 0, 0, 1,0xd996, 0x5e23);   
NLM_C45_WRITE (0, 0, 0, 1,0xd997, 0x03d2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd998, 0x001d);   
NLM_C45_WRITE (0, 0, 0, 1,0xd999, 0x2f0e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd99a, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd99b, 0x2054);   
NLM_C45_WRITE (0, 0, 0, 1,0xd99c, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd99d, 0x6ec4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd99e, 0x2064);   
NLM_C45_WRITE (0, 0, 0, 1,0xd99f, 0x3cc4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a0, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a1, 0x8ee9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a2, 0xbe0e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a3, 0xbf4e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a4, 0x5e23);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a5, 0x0382);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a6, 0x0009);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a7, 0x2fee);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a8, 0x3ffe);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9a9, 0x89e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9aa, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ab, 0x280e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ac, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ad, 0x63ae);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ae, 0x0007);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9af, 0x401e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b0, 0x99e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b1, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b2, 0x280e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b3, 0x300e);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b4, 0x63ae);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b5, 0x6f72);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b6, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b7, 0x628f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b8, 0x2844);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9b9, 0x3c04);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ba, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9bb, 0x2d62);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9bc, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9bd, 0x1e52);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9be, 0x20c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9bf, 0x3c24);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c0, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c1, 0x2ff9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c2, 0x3fd9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c3, 0x89e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c4, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c5, 0x26c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c6, 0x3c04);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c7, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c8, 0x2ff9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9c9, 0x3fa9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ca, 0x89e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9cb, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9cc, 0x2894);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9cd, 0x3c04);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ce, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9cf, 0x2f79);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d0, 0x3ff9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d1, 0x89e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d2, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d3, 0x2eb2);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d4, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d5, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d6, 0x2894);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d7, 0x3c04);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d8, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9d9, 0x2089);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9da, 0x3009);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9db, 0x99e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9dc, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9dd, 0x26c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9de, 0x3c04);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9df, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e0, 0x2009);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e1, 0x3059);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e2, 0x99e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e3, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e4, 0x20c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e5, 0x3c24);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e6, 0x64de);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e7, 0x2009);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e8, 0x3029);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9e9, 0x99e9);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ea, 0x69c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9eb, 0x6f72);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ec, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ed, 0x64d6);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ee, 0x21f7);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ef, 0x3fc7);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f0, 0x8676);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f1, 0xb505);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f2, 0x9566);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f3, 0x66c4);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f4, 0xb545);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f5, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f6, 0x628f);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f7, 0x6138);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f8, 0x5883);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9f9, 0x2062);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9fa, 0x3032);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9fb, 0x1302);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9fc, 0x2ff7);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9fd, 0x3007);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9fe, 0x8786);   
NLM_C45_WRITE (0, 0, 0, 1,0xd9ff, 0xb887);   
NLM_C45_WRITE (0, 0, 0, 1,0xda00, 0x8785);   
NLM_C45_WRITE (0, 0, 0, 1,0xda01, 0xb8c5);   
NLM_C45_WRITE (0, 0, 0, 1,0xda02, 0x5e63);   
NLM_C45_WRITE (0, 0, 0, 1,0xda03, 0x2f72);   
NLM_C45_WRITE (0, 0, 0, 1,0xda04, 0x3022);   
NLM_C45_WRITE (0, 0, 0, 1,0xda05, 0x13c2);   
NLM_C45_WRITE (0, 0, 0, 1,0xda06, 0x6f72);   
NLM_C45_WRITE (0, 0, 0, 1,0xda07, 0x1002);   
NLM_C45_WRITE (0, 0, 0, 1,0xda08, 0x0c82);   
NLM_C45_WRITE (0, 0, 0, 1,0xda09, 0x0d87);   
NLM_C45_WRITE (0, 0, 0, 1,0xda0a, 0x0e8d);   
NLM_C45_WRITE (0, 0, 0, 1,0xda0b, 0x1092);   
NLM_C45_WRITE (0, 0, 0, 1,0xda0c, 0x1198);   
NLM_C45_WRITE (0, 0, 0, 1,0xda0d, 0x129d);   
NLM_C45_WRITE (0, 0, 0, 1,0xda0e, 0x14a3);   
NLM_C45_WRITE (0, 0, 0, 1,0xda0f, 0x16a8);   
NLM_C45_WRITE (0, 0, 0, 1,0xda10, 0x17ae);   
NLM_C45_WRITE (0, 0, 0, 1,0xda11, 0x18b4);   
NLM_C45_WRITE (0, 0, 0, 1,0xda12, 0x0000);   
NLM_C45_WRITE (0, 0, 0, 1,0xda13, 0x0000);   
NLM_C45_WRITE (0, 0, 0, 1,0xd080, 0x0100);   
NLM_C45_WRITE (0, 0, 0, 1,0xd092, 0x0000);   

//sleep 400000	   # us
for(i=0;i<100000;i++) NLM_C45_PRINTF(".");

NLM_C45_WRITE (0, 0, 0, 1,0xcc08, 0x07c6);  // 5:0 = 0x6
NLM_C45_WRITE (0, 0, 0, 1,0xcc08, 0x08c6);  //11:6 = 0x23
NLM_C45_WRITE (0, 0, 0, 1,0xcc09, 0x07e8);  // 5:0 = 0x28
NLM_C45_WRITE (0, 0, 0, 1,0xcc09, 0x0b68);  //11:6 = 0x2d
NLM_C45_WRITE (0, 0, 0, 1,0xcc0e, 0x0001);  // 0:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xcc0e, 0x0000);  // 0:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2e1, 0x000f);  // 3:0 = 0xf
NLM_C45_WRITE (0, 0, 0, 1,0xc088, 0x0004);  // 3:0 = 0x4
NLM_C45_WRITE (0, 0, 0, 1,0xc290, 0x0001);  // 0:0 = 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xca01, 0x0041);  // 7:1 = 0x20
NLM_C45_WRITE (0, 0, 0, 1,0xca51, 0x0041);  // 7:1 = 0x20
NLM_C45_WRITE (0, 0, 0, 1,0xc2e8, 0x0000);  // 8:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2e9, 0x0000);  // 8:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2ea, 0x0000);  // 8:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2eb, 0x0000);  // 8:0 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2e6, 0x0800);  //11:11= 0x1
NLM_C45_WRITE (0, 0, 0, 1,0xc2e6, 0x0000);  //11:11= 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc2e0, 0x00e4);  // 7:0 = 0xe4
NLM_C45_WRITE (0, 0, 0, 1,0xc2e1, 0x000f);  //13:12= 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc20d, 0x0000);  // 9:8 = 0x0
NLM_C45_WRITE (0, 0, 0, 1,0xc012, 0x000a);  // 3:0 = 0xa
NLM_C45_WRITE (0, 0, 0, 1,0xc012, 0x00aa);  // 7:4 = 0xa
NLM_C45_WRITE (0, 0, 0, 1,0xc0f0, 0x010a);  //  
NLM_C45_WRITE (0, 0, 0, 1,0xc0f1, 0x0056);  //  #  7:0 = 0x56
NLM_C45_WRITE (0, 0, 0, 1,0xc20d, 0x0002);  //  #  1:1 = 0x1
//sleep 200000	   # us
for(i=0;i<100000;i++) NLM_C45_PRINTF(".");

