#
# Makefile for the Flattened Device Tree for Netlogic XLP Kernels
#

obj-$(CONFIG_FDT)  += simple_alloc.o
obj-$(CONFIG_FDT)  += libfdt-wrapper.o
obj-$(CONFIG_FDT)  += fdt.o fdt_ro.o fdt_wip.o fdt_sw.o fdt_rw.o fdt_strerror.o
