################################################################################

#
# Makefile for the nlm_spi4 ethernet driver
#
EXTRA_CFLAGS := -Werror

obj-$(CONFIG_NLMCOMMON_SPI4) += os_layer.o nlm_spi4.o nlm_vits_eth.o vitesse_highlevel.o \
                            vitesse_io.o vitesse_phy_ctrl.o nlm_vits_driver.o  nlm_vits_wrapper.o
